name: ESP32C3 SPI Unit Test

on:
  push:
    branches: [ "SPI_Unit_Test" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Clean build folder
        run: rm -rf build
      - uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v5.2
          target: esp32c3

      - name: Clean broken cache
        run: |
          rm -rf build
          find . -name "CMakeCache.txt" -delete

      - name: Build
        run: idf.py build
