name: ESP32C3 SPI Unit Test

on:
  push:
    branches: [ "CICD_Pytest" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Load ESP-IDF
        run: |
          source ~/esp-idf/export.sh
      - name: Clean build
        run: |
          rm -rf build
      - name: Build
        run: |
          . $HOME/esp-idf/export.sh
          idf.py build
          
